### ISSUE TITLE
Stretch reminder opens even if you're not using Chrome

### ISSUE THREAD

**Issue by cameronmarlow** [guanzgrace/stretch#9]
Opening your laptop after not using Chrome causes it to open a new tab automatically. Not sure how to best handle this, but the correct behavior should be to measure time since active.

**Comment by guanzgrace** [comment]
Fixed by querying for active tabs containing "notification.html" and closing/re-opening them. This ensures maximum one tab is open at a time. Not sure what you mean by opening laptop after not using Chrome causes it to open a new tab automatically: perhaps the alarm is firing when the computer is closed? Will look into it.
```
var popupUrl = chrome.runtime.getURL('/notification.html');
    chrome.tabs.query({url:popupUrl}, function(tabs){
        if(tabs.length > 0){
            console.log("Tab exists");
            console.log(tabs);
            chrome.tabs.remove(tabs[0].id);
            //chrome.tabs.update(tabs[0].id, {url: tabs[0].url, active:true, highlighted:true});
        }
        chrome.windows.create({ url: 'notification.html', type: "popup" });
    });
```
